<?php include('header.php'); ?>		

<h2>Balanced Brackets</h2>

<form method="post">
   
   <div class="row">
   
      <div class="form-group col-md-7">			
     	 <label for="name" >Digite os caracteres brackets:</label>		      
      	<input type="text" class="form-control" name="value" placeholder="Exemplo: [{()}](){} []">		    
      </div>
   </div>
   
   <div id="actions" class="row">
      <div class="col-md-12">	
       <input type="submit" class="btn btn-primary"/>	      
  	 </div>
   </div>
   
    <h3><?= isset($value)? $value : "" ?></h3>
   
</form>

<?php include('footer.php'); ?>	